spring:
  application:
    name: inventory-mgmt-service
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # for issue error webAllowOthers in

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

allow:
  origin: "*"